name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: muditsahni-bb2eb # Keep your project ID
  SERVICE_NAME: documentparser # Keep your service name
  REGION: asia-south2 # Keep your region

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Remove Java and Gradle setup steps since they're not needed

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: 'gke-gcloud-auth-plugin'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Create Artifact Registry Repository
        run: |
          gcloud artifacts repositories create ${{ env.SERVICE_NAME }} \
            --repository-format=docker \
            --location=${{ env.REGION }} \
            --project=${{ env.PROJECT_ID }} \
            --description="Repository for Document Parser API" \
            || true  # The '|| true' ensures the workflow continues even if the repo already exists

      - name: Get GCP Service Account Key
        run: |
          mkdir -p secrets
          gcloud secrets versions access latest --project="${{ env.PROJECT_ID }}" --secret="gcp-sa-key" > secrets/gcp-service-account-key.json

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-south2-docker.pkg.dev

      - name: Build and Push Docker image
        run: |
          IMAGE_PATH="asia-south2-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/app"
          docker build -t $IMAGE_PATH:${{ github.sha }} -t $IMAGE_PATH:latest .
          docker push $IMAGE_PATH:${{ github.sha }}
          docker push $IMAGE_PATH:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: asia-south2-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/app:${{ github.sha }}